SECTORS = {
 "PRIVATE BANK": ["HDFCBANK","ICICIBANK","AXISBANK","KOTAKBANK","INDUSINDBK"],
 "PSU BANK": ["SBIN","PNB","BANKBARODA"],
 "IT": ["TCS","INFY","WIPRO","HCLTECH","TECHM"],
 "AUTO": ["MARUTI","TATAMOTORS","EICHERMOT"],
 "PHARMA": ["SUNPHARMA","CIPLA","DRREDDY","LUPIN"],
 "FMCG": ["ITC","HINDUNILVR","NESTLEIND","BRITANNIA"],
 "METAL": ["TATASTEEL","JSWSTEEL","HINDALCO","VEDL"],
 "ENERGY": ["RELIANCE","ONGC","NTPC","BPCL","POWERGRID"],
 "REALTY": ["DLF","GODREJPROP"],
 "FINANCIAL": ["BAJFINANCE","BAJAJFINSV","SBILIFE"],
 "INFRA": ["LT","ADANIPORTS"],
 "DEFENCE": ["BEL","HAL"],
}
SECTOR_OF = {s: k for k, v in SECTORS.items() for s in v}
SYMBOLS = list(SECTOR_OF)
